import {ensureSchema,getRuntimeEnv} from "@/db/runtime";
import {isIndexer,smallJson,jobGuard,validIndexerProcessor} from "@/lib/indexer-auth";
import {chunkStatements,deleteChunks,deleteSectionChunks,promoteStagedChunks,publicIndexedDocument,seedSearchPage} from "@/lib/search-index-v2";
import {readJson,type SearchKind,type TextSection} from "@/lib/search-model";
import {visibleSearchDocument} from "@/lib/search-schema";
import {publicAttachments,storedAttachments} from "@/lib/contribution-attachments";
import {seedSources,indexExternal} from "@/lib/external-index";
import {searchLibrary} from "@/lib/search-service";
import {inputFromUrl} from "@/app/api/search/route";

const noStore={"Cache-Control":"no-store"};
const unauthorized=()=>Response.json({error:"처리기 인증이 필요합니다."},{status:401,headers:noStore});
export async function GET(request:Request){if(!isIndexer(request))return unauthorized();await ensureSchema();const {DB}=getRuntimeEnv();const action=new URL(request.url).searchParams.get("action")||"status";
  if(action==="query"){const start=performance.now();const result=await searchLibrary(DB,inputFromUrl(new URL(request.url)),true);return Response.json({...result,serverMs:performance.now()-start},{headers:noStore});}
  if(action==="sources"){const rows=await DB.prepare("SELECT * FROM search_v2_sources ORDER BY id").all();return Response.json({sources:rows.results},{headers:noStore});}
  if(action==="inventory"){const p=new URL(request.url).searchParams;const offset=Math.max(0,Number(p.get("offset")||0));const rows=await DB.prepare(`SELECT d.id,d.title,d.source_type,d.file_type,d.index_status,d.index_message,d.year,d.subject,(SELECT COUNT(*) FROM search_v2_chunks c WHERE c.document_id=d.id AND c.field='body') AS chunks FROM search_v2_documents d WHERE ${visibleSearchDocument} ORDER BY d.id LIMIT 100 OFFSET ?`).bind(offset).all();return Response.json({documents:rows.results,nextOffset:rows.results.length===100?offset+100:null},{headers:noStore});}
  const rows=await DB.batch([DB.prepare(`SELECT d.index_status AS status,COUNT(*) AS count FROM search_v2_documents d WHERE ${visibleSearchDocument} GROUP BY d.index_status`),DB.prepare("SELECT status,COUNT(*) AS count FROM search_v2_jobs GROUP BY status"),DB.prepare("SELECT key,value FROM search_v2_control"),DB.prepare("SELECT COUNT(*) AS count FROM search_v2_chunks"),DB.prepare("SELECT id,title,content_type,LENGTH(extracted_text) AS legacyCharacters FROM contributions WHERE status IN ('published','published_ai') ORDER BY id")]);return Response.json({documents:rows[0].results,jobs:rows[1].results,control:rows[2].results,chunks:rows[3].results[0],originals:rows[4].results},{headers:noStore});
}
export async function POST(request:Request){if(!isIndexer(request))return unauthorized();await ensureSchema();const {DB}=getRuntimeEnv();try{const body=await smallJson(request);const action=String(body.action||"");
  if(action==="source-seeds"){await seedSources(DB);return Response.json({ok:true},{headers:noStore});}
  if(action==="external")return Response.json(await indexExternal(DB,body),{headers:noStore});
  if(action==="retry"){const doc=await publicIndexedDocument(DB,String(body.documentId));if(!doc||doc.source_type!=="contribution")throw new Error("공개 기여 자료를 선택해 주세요.");await DB.batch([DB.prepare("UPDATE search_v2_jobs SET status='pending',attempts=0,lease_token=NULL,lease_until=0,error='',progress_json='{}' WHERE document_id=? AND content_version=?").bind(String(doc.id),Number(doc.content_version)),DB.prepare("UPDATE search_v2_documents SET index_status='pending',index_message='' WHERE id=?").bind(String(doc.id))]);return Response.json({ok:true},{headers:noStore});}
  if(action==="seed"){const kind=String(body.kind) as SearchKind;const offset=Number(body.offset||0);if(!["contribution","reference","folder","builtin"].includes(kind)||!Number.isSafeInteger(offset)||offset<0)throw new Error("자료 종류·위치를 확인해 주세요.");return Response.json(await seedSearchPage(DB,kind,offset),{headers:noStore});}
  if(action==="activate"){const active=body.active===true;const missing=await DB.prepare("SELECT COUNT(*) AS count FROM contributions c WHERE c.status IN ('published','published_ai') AND NOT EXISTS(SELECT 1 FROM search_v2_documents d WHERE d.source_type='contribution' AND d.source_id=c.id)").first<{count:number}>();if(active&&missing?.count)throw new Error("공개 자료의 기본 색인을 먼저 모두 준비해 주세요.");await DB.batch([DB.prepare("INSERT INTO search_v2_control(key,value) VALUES('active',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(active?"1":"0"),DB.prepare("INSERT INTO search_v2_control(key,value) VALUES('version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(crypto.randomUUID())]);return Response.json({active},{headers:noStore});}
  if(action==="pause"){await DB.prepare("INSERT INTO search_v2_control(key,value) VALUES('paused',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(body.paused===false?"0":"1").run();return Response.json({ok:true},{headers:noStore});}
  if(action==="claim"){
    if((await DB.prepare("SELECT value FROM search_v2_control WHERE key='paused'").first<{value:string}>())?.value==="1")return Response.json({job:null,paused:true},{headers:noStore});
    const now=Date.now(),token=crypto.randomUUID();await DB.batch([DB.prepare("UPDATE search_v2_documents SET index_status='failed',index_message='처리기가 세 번 중단되었습니다. 관리자가 다시 시도할 수 있습니다.' WHERE id IN(SELECT document_id FROM search_v2_jobs WHERE status='processing' AND lease_until<? AND attempts>=3)").bind(now),DB.prepare("UPDATE search_v2_jobs SET status='failed',lease_token=NULL,error='처리기 중단 후 재시도 한도' WHERE status='processing' AND lease_until<? AND attempts>=3").bind(now)]);const job=await DB.prepare(`UPDATE search_v2_jobs SET status='processing',attempts=attempts+1,lease_token=?,lease_until=?,updated_at=CURRENT_TIMESTAMP WHERE id=(SELECT j.id FROM search_v2_jobs j JOIN search_v2_documents d ON d.id=j.document_id WHERE j.content_version=d.content_version AND ${visibleSearchDocument} AND j.attempts<3 AND (j.status IN ('pending','retry') OR (j.status='processing' AND j.lease_until<?)) ORDER BY CASE WHEN instr(d.file_type,'zip')>0 THEN 0 WHEN EXISTS(SELECT 1 FROM contributions c WHERE c.id=d.source_id AND LENGTH(c.extracted_text)>=100000) THEN 1 ELSE 2 END,j.updated_at,j.id LIMIT 1) RETURNING *`).bind(token,now+120000,now).first<Record<string,unknown>>();
    if(!job)return Response.json({job:null},{headers:noStore});const doc=await publicIndexedDocument(DB,String(job.document_id));if(!doc)throw new Error("공개 자료가 변경되었습니다.");const source=await DB.prepare("SELECT attachments_json,original_name,content_type,object_key FROM contributions WHERE id=? AND status IN ('published','published_ai') AND text_only=0").bind(String(doc.source_id)).first<Record<string,unknown>>();const attachments=source?publicAttachments(storedAttachments(String(source.attachments_json||""),{originalName:String(source.original_name),contentType:String(source.content_type),objectKey:String(source.object_key)})):[];
    await DB.prepare("UPDATE search_v2_documents SET index_status='processing' WHERE id=? AND content_version=?").bind(String(doc.id),Number(job.content_version)).run();return Response.json({job:{id:job.id,documentId:job.document_id,version:job.content_version,leaseToken:token,progress:readJson(job.progress_json,{}),attachments:attachments.map((a,i)=>({...a,url:`/api/files?id=${encodeURIComponent(String(doc.source_id))}&attachment=${i}`}))}},{headers:noStore});
  }
  const jobId=String(body.jobId||""),leaseToken=String(body.leaseToken||"");const job=await DB.prepare(`SELECT j.* FROM search_v2_jobs j JOIN search_v2_documents d ON d.id=j.document_id WHERE j.id=? AND j.lease_token=? AND j.status='processing' AND j.content_version=d.content_version AND ${visibleSearchDocument}`).bind(jobId,leaseToken).first<Record<string,unknown>>();if(!job)return Response.json({error:"처리 작업이 변경되었거나 종료되었습니다."},{status:409,headers:noStore});
  if(!validIndexerProcessor(action,body,readJson(job.progress_json,{})))return Response.json({error:"처리기를 최신 버전으로 다시 시작해 주세요."},{status:409,headers:noStore});
  const id=String(job.document_id);const guard=jobGuard(DB,jobId,leaseToken);const lease=DB.prepare("UPDATE search_v2_jobs SET lease_until=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND lease_token=?").bind(Date.now()+120000,jobId,leaseToken);
  if(action==="heartbeat"){await DB.batch([guard.start,lease,guard.end]);return Response.json({ok:true},{headers:noStore});}
  if(action==="release"){await DB.batch([guard.start,DB.prepare("UPDATE search_v2_jobs SET status='retry',attempts=MAX(0,attempts-1),lease_token=NULL,lease_until=0 WHERE id=?").bind(jobId),DB.prepare("UPDATE search_v2_documents SET index_status='pending' WHERE id=? AND content_version=?").bind(id,Number(job.content_version)),guard.end]);return Response.json({ok:true},{headers:noStore});}
  if(action==="page"){
    const sections=Array.isArray(body.sections)?body.sections as TextSection[]:[];if(sections.length>10||sections.some(s=>typeof s.text!=="string"||Array.from(s.text).length>16000||!Number.isSafeInteger(s.ordinal)||Number(s.ordinal)<0||s.page!==undefined&&(!Number.isSafeInteger(s.page)||s.page<1)||s.attachment!==undefined&&(!Number.isSafeInteger(s.attachment)||s.attachment<0)||s.path!==undefined&&(typeof s.path!=="string"||s.path.length>500)))throw new Error("본문 구간을 확인해 주세요.");
    const progress=body.progress&&typeof body.progress==="object"?JSON.stringify(body.progress):"{}";if(progress.length>16000)throw new Error("진행 정보가 너무 큽니다.");
    // In one D1 transaction, acquire a job-version guard before modifying chunks.
    const statements=[guard.start,lease,...(body.reset===true?deleteChunks(DB,id,"staging"):[]),...(body.resetSection===true&&sections.length===1?deleteSectionChunks(DB,id,sections[0],"staging"):[]),...chunkStatements(DB,id,sections,"staging"),DB.prepare("UPDATE search_v2_jobs SET progress_json=? WHERE id=? AND lease_token=?").bind(progress,jobId,leaseToken),guard.end];if(statements.length>250)throw new Error("한 번에 더 작은 본문 구간을 보내 주세요.");await DB.batch(statements);return Response.json({ok:true},{headers:noStore});
  }
  if(action==="finish"||action==="fail"){
    const state=action==="fail"?"failed":["completed","partial","unsupported"].includes(String(body.status))?String(body.status):"partial";const error=String(body.message||"").slice(0,500);const attempts=Number(job.attempts);const next=action==="fail"&&attempts<3?"retry":state;
    const hash=typeof body.hash==="string"&&/^[a-f0-9]{64}$/.test(body.hash)?"sha256:"+body.hash:id;
    await DB.batch([guard.start,...(action==="finish"?promoteStagedChunks(DB,id):[]),DB.prepare("UPDATE search_v2_jobs SET status=?,attempts=?,error=?,lease_token=NULL,lease_until=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND lease_token=?").bind(next,attempts,error,jobId,leaseToken),DB.prepare("UPDATE search_v2_documents SET index_status=?,index_message=?,duplicate_key=CASE WHEN ?='finish' THEN ? ELSE duplicate_key END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND content_version=?").bind(state,error,action,hash,id,Number(job.content_version)),DB.prepare("INSERT INTO search_v2_control(key,value) VALUES('version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(crypto.randomUUID()),guard.end]);return Response.json({ok:true,status:next},{headers:noStore});
  }
  throw new Error("지원하지 않는 처리 요청입니다.");
}catch(error){return Response.json({error:error instanceof Error?error.message:"처리 요청을 완료하지 못했습니다."},{status:400,headers:noStore});}}
