CREATE TABLE ocr_cache (
  file_hash TEXT PRIMARY KEY,
  extracted_text TEXT NOT NULL,
  pages INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
