"use client";

import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { ConceptGraph3D, ConceptGraph3DNode } from "@/lib/custom-materials";

export const emptyConceptGraph3D = (): ConceptGraph3D => ({ title: "", nodes: [], edges: [], camera: { x: 4, y: 4, z: 7, zoom: 1 } });

export function ConceptGraph3DStudio({ graph, onChange, readOnly = false }: { graph: ConceptGraph3D; onChange?: (graph: ConceptGraph3D) => void; readOnly?: boolean }) {
  const webgl = useRef<HTMLCanvasElement>(null); const labels = useRef<HTMLCanvasElement>(null); const [supported, setSupported] = useState(true); const [selected, setSelected] = useState(""); const [linkFrom, setLinkFrom] = useState("");
  const update = (next: ConceptGraph3D) => onChange?.(next);
  useEffect(() => {
    const canvas = webgl.current; const labelCanvas = labels.current; if (!canvas || !labelCanvas) return;
    let renderer: THREE.WebGLRenderer; try { renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true }); } catch { setSupported(false); return; }
    const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(42, 1, .1, 100); camera.position.set(graph.camera.x, graph.camera.y, graph.camera.z); camera.zoom = graph.camera.zoom; camera.updateProjectionMatrix(); camera.lookAt(0,0,0);
    const group = new THREE.Group(); scene.add(group); const grid = new THREE.GridHelper(20, 20, 0x4f8877, 0x276354); scene.add(grid);
    const nodeObjects = new Map<string, THREE.Object3D>();
    graph.nodes.forEach((node) => { const geometry = node.shape === "box" ? new THREE.BoxGeometry(.48,.48,.48) : new THREE.SphereGeometry(node.shape === "text" ? .16 : .3, 22, 16); const material = new THREE.MeshStandardMaterial({ color: node.id === selected ? 0xef2d75 : node.shape === "text" ? 0xf4fbff : 0x79d8c1, emissive: node.id === selected ? 0x3c0018 : 0x001810, roughness: .45 }); const mesh = new THREE.Mesh(geometry, material); mesh.position.set(node.x,node.y,node.z); group.add(mesh); nodeObjects.set(node.id, mesh); });
    graph.edges.forEach((edge) => { const from = graph.nodes.find((node) => node.id === edge.from); const to = graph.nodes.find((node) => node.id === edge.to); if (!from || !to) return; const start = new THREE.Vector3(from.x,from.y,from.z); const end = new THREE.Vector3(to.x,to.y,to.z); if (edge.directed) { const direction = end.clone().sub(start); const length = direction.length(); if (length > .05) group.add(new THREE.ArrowHelper(direction.normalize(), start, length, 0xef2d75, .22, .12)); } else { group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,end]), new THREE.LineBasicMaterial({ color: 0xb9e8dc }))); } });
    scene.add(new THREE.AmbientLight(0xffffff, 1.7)); const light = new THREE.DirectionalLight(0xffffff, 2); light.position.set(5,8,7); scene.add(light);
    const resize = () => { const rect = canvas.getBoundingClientRect(); const ratio = Math.max(1,window.devicePixelRatio || 1); renderer.setPixelRatio(ratio); renderer.setSize(rect.width,rect.height,false); labelCanvas.width = Math.round(rect.width*ratio); labelCanvas.height = Math.round(rect.height*ratio); labelCanvas.style.width=`${rect.width}px`; labelCanvas.style.height=`${rect.height}px`; camera.aspect=rect.width/rect.height; camera.updateProjectionMatrix(); }; const observer = new ResizeObserver(resize); observer.observe(canvas); resize();
    const pointers = new Map<number,{x:number;y:number}>(); let lastDistance=0; let lastCenter:{x:number;y:number}|null=null; let cameraDirty=false; let wheelTimer=0;
    const persistCamera=()=>{ if(!cameraDirty||readOnly||!onChange)return; cameraDirty=false; onChange({...graph,camera:{x:camera.position.x,y:camera.position.y,z:camera.position.z,zoom:camera.zoom}}); };
    const down=(event:PointerEvent)=>{ pointers.set(event.pointerId,{x:event.clientX,y:event.clientY}); canvas.setPointerCapture(event.pointerId); };
    const move=(event:PointerEvent)=>{ const before=pointers.get(event.pointerId); if(!before)return; pointers.set(event.pointerId,{x:event.clientX,y:event.clientY}); const values=[...pointers.values()]; if(values.length===1){ group.rotation.y+=(event.clientX-before.x)*.009; group.rotation.x+=(event.clientY-before.y)*.009; } else if(values.length>=2){ const [a,b]=values; const distance=Math.hypot(a.x-b.x,a.y-b.y); const center={x:(a.x+b.x)/2,y:(a.y+b.y)/2}; if(lastDistance){ camera.zoom=Math.max(.4,Math.min(3,camera.zoom*(distance/lastDistance))); camera.updateProjectionMatrix(); cameraDirty=true; } if(lastCenter){ camera.position.x-=(center.x-lastCenter.x)*.008; camera.position.y+=(center.y-lastCenter.y)*.008; cameraDirty=true; } lastDistance=distance; lastCenter=center; } };
    const up=(event:PointerEvent)=>{ pointers.delete(event.pointerId); if(pointers.size<2){lastDistance=0;lastCenter=null;} if(!pointers.size)persistCamera(); }; const wheel=(event:WheelEvent)=>{ event.preventDefault(); camera.zoom=Math.max(.4,Math.min(3,camera.zoom*(event.deltaY>0?.92:1.08))); camera.updateProjectionMatrix(); cameraDirty=true; window.clearTimeout(wheelTimer); wheelTimer=window.setTimeout(persistCamera,280); };
    canvas.addEventListener("pointerdown",down); canvas.addEventListener("pointermove",move); canvas.addEventListener("pointerup",up); canvas.addEventListener("pointercancel",up); canvas.addEventListener("wheel",wheel,{passive:false});
    let frame=0; const draw=()=>{ renderer.render(scene,camera); const context=labelCanvas.getContext("2d"); const rect=canvas.getBoundingClientRect(); if(context){ const ratio=Math.max(1,window.devicePixelRatio||1); context.setTransform(ratio,0,0,ratio,0,0); context.clearRect(0,0,rect.width,rect.height); context.font="700 12px Pretendard, sans-serif"; context.textAlign="center"; graph.nodes.forEach((node)=>{ const object=nodeObjects.get(node.id); if(!object)return; const point=object.getWorldPosition(new THREE.Vector3()).project(camera); const x=(point.x*.5+.5)*rect.width; const y=(-point.y*.5+.5)*rect.height; const label=node.label; const width=Math.min(170,Math.max(34,context.measureText(label || " ").width+16)); context.fillStyle=node.id===selected?"#ef2d75":"rgba(4,57,44,.9)"; context.fillRect(x-width/2,y-31,width,22); context.fillStyle="#fff"; context.fillText(label,x,y-20); }); } frame=requestAnimationFrame(draw); }; draw();
    return()=>{ window.clearTimeout(wheelTimer); cancelAnimationFrame(frame); observer.disconnect(); canvas.removeEventListener("pointerdown",down); canvas.removeEventListener("pointermove",move); canvas.removeEventListener("pointerup",up); canvas.removeEventListener("pointercancel",up); canvas.removeEventListener("wheel",wheel); scene.traverse((object)=>{ if(object instanceof THREE.Mesh||object instanceof THREE.Line){ object.geometry.dispose(); const material=object.material; if(Array.isArray(material))material.forEach((item)=>item.dispose());else material.dispose(); }}); renderer.dispose(); };
  },[graph,selected,onChange,readOnly]);
  if(!supported) return <div className="concept-map-fallback"><strong>{graph.title}</strong><p>이 기기에서는 3D 보기를 지원하지 않아 목록으로 표시합니다.</p><ul>{graph.nodes.map((node)=><li key={node.id}>{node.label}</li>)}</ul></div>;
  const selectNode=(id:string)=>{ if(linkFrom&&linkFrom!==id&&!readOnly){ update({...graph,edges:[...graph.edges,{id:`edge-${Date.now()}`,from:linkFrom,to:id,label:"",directed:true}]});setLinkFrom(""); } setSelected(id); };
  const addNode=(shape:ConceptGraph3DNode["shape"])=>{ const id=`node-${Date.now()}`; update({...graph,nodes:[...graph.nodes,{id,shape,x:0,y:.5,z:0,label:""}]});setSelected(id); };
  const selectedNode=graph.nodes.find((node)=>node.id===selected);
  return <section className={`graph3d-studio ${readOnly?"readonly":""}`}><header><label><span>3D 개념도 제목</span>{readOnly?<strong>{graph.title}</strong>:<input value={graph.title} onChange={(event)=>update({...graph,title:event.target.value})} placeholder="제목" />}</label>{!readOnly&&<div><button type="button" onClick={()=>addNode("sphere")}>● 구</button><button type="button" onClick={()=>addNode("box")}>■ 상자</button><button type="button" onClick={()=>addNode("text")}>T 텍스트</button></div>}</header><div className="graph3d-stage"><canvas ref={webgl} aria-label="3D 개념 그래프" /><canvas ref={labels} aria-hidden="true" /></div><div className="graph3d-node-list">{graph.nodes.map((node)=><button type="button" className={selected===node.id?"active":""} key={node.id} onClick={()=>selectNode(node.id)}>{node.label||" "}<small>{node.x}, {node.y}, {node.z}</small></button>)}</div>{!readOnly&&selectedNode&&<div className="graph3d-inspector"><label>문구<input value={selectedNode.label} onChange={(event)=>update({...graph,nodes:graph.nodes.map((node)=>node.id===selected?{...node,label:event.target.value}:node)})} /></label>{(["x","y","z"] as const).map((axis)=><label key={axis}>{axis.toUpperCase()}<input type="range" min="-6" max="6" step=".5" value={selectedNode[axis]} onChange={(event)=>update({...graph,nodes:graph.nodes.map((node)=>node.id===selected?{...node,[axis]:Number(event.target.value)}:node)})} /></label>)}<button type="button" className={linkFrom===selected?"active":""} onClick={()=>setLinkFrom(selected)}>연결 시작</button><button type="button" onClick={()=>{update({...graph,nodes:graph.nodes.filter((node)=>node.id!==selected),edges:graph.edges.filter((edge)=>edge.from!==selected&&edge.to!==selected)});setSelected("");}}>삭제</button></div>}{!readOnly&&graph.edges.map((edge)=><label className="graph3d-edge" key={edge.id}><span>연결 설명</span><input value={edge.label} onChange={(event)=>update({...graph,edges:graph.edges.map((item)=>item.id===edge.id?{...item,label:event.target.value}:item)})} /></label>)}{readOnly&&graph.edges.length>0&&<div className="graph3d-relations">{graph.edges.map((edge)=><p key={edge.id}><span>{graph.nodes.find((node)=>node.id===edge.from)?.label||"빈 개념"}</span><b>{edge.directed?"→":"—"}</b><span>{graph.nodes.find((node)=>node.id===edge.to)?.label||"빈 개념"}</span><small>{edge.label}</small></p>)}</div>}</section>;
}
