"use client";
import {useEffect,useRef,useState,type ReactNode} from "react";
import {MaterialPlayer,SourceTextPreview} from "./MaterialPlayer";
import {isTextSource,isWebPackage} from "@/lib/upload-types";
import {statusLabels,type IndexStatus,type TextSection} from "@/lib/search-model";
import "./document-viewer.css";
type Attachment={originalName:string;contentType:string;url:string};
type Props={id:string;sourceType?:string;title:string;attachments:Attachment[];fallback?:string};
export default function DocumentViewer({id,sourceType="contribution",title,attachments,fallback}:Props){
 const [index,setIndex]=useState(0),[expanded,setExpanded]=useState(false),[initialPage,setInitialPage]=useState(1),[matchedPath,setMatchedPath]=useState('');
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;const p=new URLSearchParams(location.search);setIndex(Math.min(attachments.length-1,Math.max(0,Number(p.get('attachment'))||0)));setInitialPage(Math.max(1,Number(p.get('page'))||1));setMatchedPath(p.get('path')||'');});return()=>{active=false}},[id,attachments.length]);
 useEffect(()=>{if(!expanded)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setExpanded(false)};addEventListener('keydown',close);return()=>{document.body.style.overflow=before;removeEventListener('keydown',close)}},[expanded]);
 const file=attachments[index],isImage=file?.contentType.startsWith('image/'),isPdf=file&&(file.contentType==='application/pdf'||/\.pdf$/i.test(file.originalName));
 return <section className={'document-viewer'+(expanded?' document-expanded':'')} aria-label="원본 보기"><div className="document-toolbar"><select aria-label="첨부 파일" value={Math.max(0,index)} onChange={e=>{const value=Number(e.target.value);setIndex(value);setInitialPage(1);setMatchedPath('');const url=new URL(location.href);url.searchParams.set('attachment',String(value));['page','path','line'].forEach(k=>url.searchParams.delete(k));history.replaceState({},'',url.pathname+url.search);}}>{attachments.map((a,i)=><option key={a.url} value={i}>{i+1}. {a.originalName}</option>)}</select><div>{file&&<a href={file.url} download>원본 다운로드</a>}<button onClick={()=>setExpanded(v=>!v)} aria-pressed={expanded}>{expanded?'전체 화면 해제':'크게 보기'}</button></div></div>
 {file&&isWebPackage(file.originalName)&&!matchedPath?<MaterialPlayer sourceId={id} attachment={index}/>:isImage?<ImageDocument key={file.url} url={file.url} id={id} attachment={index} title={title}/>:isPdf?<PdfDocument key={file.url} url={file.url} initialPage={initialPage}/>:file?.contentType.startsWith('video/')?<video src={file.url} controls playsInline preload="metadata"><track kind="captions"/></video>:file?.contentType.startsWith('audio/')?<audio src={file.url} controls preload="metadata"><track kind="captions"/></audio>:<IndexedText sourceType={sourceType} key={id+':'+index} id={id} attachment={index} file={file} fallback={fallback}/>}
 </section>;
}
function ZoomStage({width,height,children,onScale}:{width:number;height:number;children:ReactNode;onScale?:(scale:number)=>void}){
 const stage=useRef<HTMLDivElement>(null),[box,setBox]=useState({width:300,height:400}),[zoom,setZoom]=useState(1),[mode,setMode]=useState<'fit'|'width'>('fit'),[pan,setPan]=useState({x:0,y:0});
 const points=useRef(new Map<number,{x:number;y:number}>()),gesture=useRef<{distance:number;zoom:number}|null>(null);
 useEffect(()=>{const el=stage.current;if(!el)return;const observer=new ResizeObserver(([e])=>setBox({width:e.contentRect.width,height:e.contentRect.height}));observer.observe(el);return()=>observer.disconnect()},[]);
 const base=mode==='width'?box.width/Math.max(1,width):Math.min(box.width/Math.max(1,width),box.height/Math.max(1,height)),scale=base*zoom;
 useEffect(()=>{onScale?.(scale)},[scale,onScale]);

 function reset(next:'fit'|'width'='fit'){setMode(next);setZoom(1);setPan({x:0,y:0});}
 // The application region implements keyboard panning as well as pointer gestures.
 // eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex
 return <><div className="document-controls"><button onClick={()=>reset('fit')}>전체 맞춤</button><button onClick={()=>reset('width')}>너비 맞춤</button><button aria-label="축소" onClick={()=>setZoom(z=>Math.max(.5,z/1.3))}>−</button><span aria-live="polite">{Math.round(zoom*100)}%</span><button aria-label="확대" onClick={()=>setZoom(z=>Math.min(8,z*1.3))}>＋</button><button onClick={()=>reset()}>초기화</button></div><div ref={stage} className="document-zoom-stage" role="application" aria-roledescription="원본 확대·이동" tabIndex={0} aria-label="두 손가락으로 확대하거나 끌어서 이동. 전체 맞춤 버튼으로 초기화." onKeyDown={e=>{const step=40;if(e.key==='ArrowLeft')setPan(p=>({...p,x:p.x+step}));if(e.key==='ArrowRight')setPan(p=>({...p,x:p.x-step}));if(e.key==='ArrowUp')setPan(p=>({...p,y:p.y+step}));if(e.key==='ArrowDown')setPan(p=>({...p,y:p.y-step}));}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.current.size===2){const[a,b]=[...points.current.values()];gesture.current={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom};}}} onPointerMove={e=>{const old=points.current.get(e.pointerId);if(!old)return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.current.size===2&&gesture.current){const[a,b]=[...points.current.values()];setZoom(Math.min(8,Math.max(.5,gesture.current.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,gesture.current.distance))));}else setPan(p=>({x:p.x+e.clientX-old.x,y:p.y+e.clientY-old.y}));}} onPointerUp={e=>{points.current.delete(e.pointerId);gesture.current=null}} onPointerCancel={e=>{points.current.delete(e.pointerId);gesture.current=null}}><div className="document-page-surface" style={{width,height,left:(box.width-width*scale)/2+pan.x,top:(box.height-height*scale)/2+pan.y,transform:`scale(${scale})`}}>{children}</div></div></>;
}
function ImageDocument({url,id,attachment,title}:{url:string;id:string;attachment:number;title:string}){
 const preview='/api/search/preview?id='+encodeURIComponent('contribution:'+id)+'&kind=preview';
 const [size,setSize]=useState({width:1000,height:1400,loaded:false}),[source,setSource]=useState(attachment===0?preview:url),[original,setOriginal]=useState(attachment!==0);
 return <ZoomStage width={size.width} height={size.height} onScale={scale=>{if(scale>1&&!original){setOriginal(true);setSource(url);}}}><img src={source} alt={title+' 원본'} draggable={false} onLoad={e=>{const width=e.currentTarget.naturalWidth,height=e.currentTarget.naturalHeight;setSize(current=>current.loaded?current:{width,height,loaded:true});}} onError={()=>{setSource(url);setOriginal(true)}}/></ZoomStage>;
}

function PdfDocument({url,initialPage}:{url:string;initialPage:number}){
 const [doc,setDoc]=useState<import('pdfjs-dist').PDFDocumentProxy|null>(null),[page,setPage]=useState(initialPage),[size,setSize]=useState({width:595,height:842}),[error,setError]=useState(''),[busy,setBusy]=useState(true),[renderScale,setRenderScale]=useState(1.5);const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let active=true,task:import('pdfjs-dist').PDFDocumentLoadingTask|undefined;void import('pdfjs-dist').then(async pdf=>{const worker=await import('pdfjs-dist/build/pdf.worker.min.mjs?url');pdf.GlobalWorkerOptions.workerSrc=worker.default;task=pdf.getDocument({url,rangeChunkSize:65536,disableAutoFetch:true,disableStream:true});const loaded=await task.promise;if(active){setDoc(loaded);setPage(Math.min(initialPage,loaded.numPages));}}).catch(e=>{if(active){setError(e.message||'PDF를 열지 못했습니다.');setBusy(false)}});return()=>{active=false;void task?.destroy()}},[url,initialPage]);
 useEffect(()=>{if(!doc||!canvas.current)return;let active=true,render:import('pdfjs-dist').RenderTask|undefined,current:import('pdfjs-dist').PDFPageProxy|undefined;void doc.getPage(page).then(async pdfPage=>{if(active){setBusy(true);setError('');}current=pdfPage;if(!active||!canvas.current)return;const natural=pdfPage.getViewport({scale:1});setSize({width:natural.width,height:natural.height});const scale=Math.min(Math.max(1,renderScale)*Math.min(devicePixelRatio||1,2),Math.sqrt(16000000/(natural.width*natural.height)));const viewport=pdfPage.getViewport({scale});const target=canvas.current;target.width=Math.ceil(viewport.width);target.height=Math.ceil(viewport.height);render=pdfPage.render({canvas:target,canvasContext:target.getContext('2d')!,viewport});await render.promise;if(active)setBusy(false);}).catch(e=>{if(active&&e.name!=='RenderingCancelledException'){setError('이 페이지를 표시하지 못했습니다. 원본 다운로드를 이용해 주세요.');setBusy(false)}});return()=>{active=false;render?.cancel();void render?.promise.catch(()=>{}).finally(()=>current?.cleanup());if(!render)current?.cleanup();}},[doc,page,renderScale]);
 return <><div className="document-controls"><button disabled={!doc||page<=1} onClick={()=>setPage(p=>p-1)}>← 이전 쪽</button><label>페이지 <input type="number" min={1} max={doc?.numPages||1} value={page} onChange={e=>setPage(Math.min(doc?.numPages||1,Math.max(1,Number(e.target.value)||1)))}/></label><span>/ {doc?.numPages||'…'}</span><button disabled={!doc||page>=doc.numPages} onClick={()=>setPage(p=>p+1)}>다음 쪽 →</button></div>{error&&<p role="alert">{error}</p>}<ZoomStage key={page} width={size.width} height={size.height} onScale={scale=>{const next=Math.min(4,Math.max(1.5,Math.ceil(scale)));if(next!==renderScale)setRenderScale(next)}}><canvas ref={canvas} aria-label={`PDF ${page}쪽`} style={{width:'100%',height:'100%'}}/></ZoomStage>{busy&&<p className="document-loading" role="status">페이지를 불러오는 중…</p>}</>;
}
function IndexedText({id,sourceType,attachment,file,fallback}:{id:string;sourceType:string;attachment:number;file?:Attachment;fallback?:string}){
 const [sections,setSections]=useState<TextSection[]>([]),[offset,setOffset]=useState(0),[next,setNext]=useState<number|null>(null),[message,setMessage]=useState('본문을 불러오는 중…'),[failed,setFailed]=useState(false);
 useEffect(()=>{const controller=new AbortController(),p=new URLSearchParams({id:sourceType+':'+id,...(file?{attachment:String(Math.max(0,attachment))}:{}),offset:String(offset)}),location=new URLSearchParams(window.location.search);if(location.has('path'))p.set('path',location.get('path')!);if(location.has('line'))p.set('line',location.get('line')!);if(location.has('page'))p.set('page',location.get('page')!);fetch('/api/search/text?'+p,{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}).then(data=>{setSections(current=>offset?[...current,...data.sections]:data.sections);setNext(data.nextOffset);setMessage(data.message||statusLabels[data.status as IndexStatus]||'');}).catch(()=>{if(!controller.signal.aborted){setFailed(true);setMessage('추출한 본문이 아직 없습니다. 원본은 다운로드할 수 있습니다.')}});return()=>controller.abort()},[id,sourceType,attachment,offset]);
 return <div className="indexed-text"><p role="status">{message}</p>{sections.map((s,i)=><section key={i}><small>{s.page?`${s.page}쪽`:s.path||`구간 ${i+1}`}{s.line?' · '+s.line+'줄부터':''}</small><div role="textbox" aria-readonly="true" aria-label="추출 본문" tabIndex={0}><pre>{s.text}</pre></div></section>)}{!sections.length&&failed&&(file&&isTextSource(file.originalName,file.contentType)?<SourceTextPreview url={file.url}/>:fallback?<pre>{fallback}</pre>:null)}{next!==null&&<button onClick={()=>setOffset(next)}>다음 본문 구간 읽기</button>}</div>;
}
