"use client";
import {useEffect,useRef,useState} from "react";
import {statusLabels,type SearchHit,type SearchResponse} from "@/lib/search-model";
import "./search-v2.css";
const fields=[['subject','과목'],['year','연도'],['school','학교'],['grade','학년'],['filetype','파일 형식']] as const;
function Highlight({text}:{text:string}){return <>{text.split(/(\[\[.*?\]\])/g).map((p,i)=>p.startsWith('[[')?<mark key={i}>{p.slice(2,-2)}</mark>:p)}</>;}
export function SearchExplorer(){
 const [params,setParams]=useState(''),[ready,setReady]=useState(false),[draft,setDraft]=useState(''),[data,setData]=useState<SearchResponse|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,retry]=useState(0),[suggestions,setSuggestions]=useState<Array<{text:string;kind:string}>>([]),[focus,setFocus]=useState(false),[composing,setComposing]=useState(false);
 const form=useRef<HTMLFormElement>(null),requestNo=useRef(0);
 useEffect(()=>{const sync=()=>{const p=new URLSearchParams(location.search);['material','attachment','page','path','line'].forEach(k=>p.delete(k));setParams(p.toString());setDraft(p.get('q')||'');setReady(true);};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 const p=new URLSearchParams(params);
 function navigate(next:URLSearchParams){window.history.pushState({},'',`/?${next}`);setParams(next.toString());setDraft(next.get('q')||'');setFocus(false);}
 function search(value=draft){const next=new URLSearchParams(location.search);next.set('q',value.trim());next.delete('cursor');next.delete('duplicates');navigate(next);}
 useEffect(()=>{if(!ready)return;const controller=new AbortController(),number=++requestNo.current;queueMicrotask(()=>{if(!controller.signal.aborted){setBusy(true);setError('');}});const start=performance.now();fetch('/api/search?'+params,{signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||'검색을 완료하지 못했습니다.');return body;}).then(body=>{if(number!==requestNo.current)return;setData(body);performance.measure('dcl-search-to-result',{start,end:performance.now()});}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setData(null);}}).finally(()=>{if(number===requestNo.current)setBusy(false);});return()=>controller.abort();},[params,ready,revision]);
 useEffect(()=>{if(composing||Array.from(draft.trim()).length<2)return;const controller=new AbortController();const timer=setTimeout(()=>{void fetch('/api/search/suggest?q='+encodeURIComponent(draft),{signal:controller.signal}).then(r=>r.ok?r.json():{suggestions:[]}).then(x=>setSuggestions(x.suggestions||[])).catch(()=>{});},180);return()=>{clearTimeout(timer);controller.abort();};},[draft,composing]);
 function update(key:string,value:string){const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);next.delete('cursor');if(key!=='duplicates')next.delete('duplicates');navigate(next);}
 function href(hit:SearchHit){const next=new URLSearchParams(params);next.set('material',hit.sourceType+':'+hit.id);for(const [k,v]of Object.entries(hit.matchLocation||{}))if(['attachment','page','path','line'].includes(k)&&v!==undefined)next.set(k,String(v));return '/?'+next;}
 return <main className="search-explorer" id="explore"><header><p className="eyebrow">DUMB CAN LEARN</p><h1>배우고 싶은 것을 찾아보세요.</h1><p>문서 속 한 문장부터 시험지, 코드, 학습 게임까지.</p></header>
 <form ref={form} role="search" className="search-v2-form" onSubmit={e=>{e.preventDefault();if(!composing)search();}}><div className="search-input-wrap"><input aria-label="자료 검색" maxLength={160} placeholder="보인고 2026 국어, 관성, 현재완료…" value={draft} onChange={e=>setDraft(e.target.value)} onFocus={()=>setFocus(true)} onBlur={()=>setTimeout(()=>setFocus(false),120)} onCompositionStart={()=>setComposing(true)} onCompositionEnd={()=>setComposing(false)} onKeyDown={e=>{if(e.key==='Escape')setFocus(false);if(e.key==='Enter'&&(e.nativeEvent.isComposing||composing))e.preventDefault();}} aria-autocomplete="list" autoComplete="off"/><button type="submit">검색</button>{focus&&!composing&&draft.trim().length>=2&&suggestions.length>0&&<ul className="search-suggestions" aria-label="검색어 제안">{suggestions.map(s=><li key={s.text}><button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>search(s.text)}>{s.text}<small>{s.kind==='correction'?'이 단어를 찾으셨나요?':s.kind==='term'?'교육 용어':'자료 제목'}</small></button></li>)}</ul>}</div></form>
 <details className="search-filter-panel" open={fields.some(([k])=>p.has(k))}><summary>과목·연도·학교로 좁히기</summary><div className="search-filters">{fields.map(([key,label])=><label key={key}>{label}{key==='subject'?<select value={p.get(key)||''} onChange={e=>update(key,e.target.value)}><option value="">전체</option>{(data?.subjects||[]).map(s=><option key={s}>{s}</option>)}</select>:<input key={params+key} defaultValue={p.get(key)||''} aria-label={label} placeholder={key==='year'?'2026':key==='filetype'?'pdf':''} onBlur={e=>{if(e.target.value!==(p.get(key)||''))update(key,e.target.value);}} onKeyDown={e=>{if(e.key==='Enter')update(key,e.currentTarget.value);}}/>}</label>)}<label>자료 종류<select value={p.get('type')||''} onChange={e=>update('type',e.target.value)}><option value="">전체</option><option value="contribution">기여 자료</option><option value="folder">공개 폴더</option><option value="reference">참고 사이트</option><option value="builtin">기본 학습 자료</option></select></label></div><p>&quot;정확한 문구&quot; · -제외어 · 과목:국어 · 연도:2026 · 학교:보인고 · filetype:pdf · site:ebsi.co.kr</p></details>
 <div className="search-result-bar"><p role="status">{busy?'검색 중…':error?'검색 오류':`${Number(data?.total??data?.results?.length??0).toLocaleString()}개 자료`}</p><label>정렬 <select aria-label="검색 정렬" value={p.get('sort')||'relevance'} onChange={e=>update('sort',e.target.value)}><option value="relevance">관련도</option><option value="newest">최신순</option><option value="views">조회수순</option></select></label></div>
 {error?<div role="alert" className="search-error"><p>{error}</p><button onClick={()=>retry(v=>v+1)}>다시 시도</button>{p.has('cursor')&&<button onClick={()=>update('cursor','')}>첫 페이지부터 보기</button>}</div>:<section aria-label="검색 결과" aria-busy={busy} className="search-result-list">{data?.results?.map(hit=><article key={hit.sourceType+':'+hit.id} className="search-result"><div className="search-result-copy"><div className="search-result-source">{hit.sourceType==='folder'?'폴더 · ':''}{hit.sourceName||'덤캔런'}{hit.fileType&&' · '+hit.fileType.toUpperCase()}</div><a href={href(hit)}><h2>{hit.title}</h2></a><p className="search-snippet"><Highlight text={hit.searchSnippet||hit.description||''}/></p><div className="search-result-tags">{[hit.subject,hit.year,hit.school].filter(Boolean).map((v,i)=><span key={i}>{v}</span>)}<span title={hit.indexMessage}>{statusLabels[hit.indexStatus]||'제목·설명 검색'}</span>{hit.matchLocation?.page&&<span>{hit.matchLocation.page}쪽 일치</span>}{hit.matchLocation?.path&&<span>{hit.matchLocation.path}{hit.matchLocation.line?':'+hit.matchLocation.line:''}</span>}</div>{hit.duplicateCount>1&&!p.has('duplicates')&&<button className="search-duplicates" onClick={()=>update('duplicates',hit.duplicateKey)}>동일 원문 등록본 {hit.duplicateCount}개 보기</button>}</div>{hit.thumbnailUrl&&<a href={href(hit)} tabIndex={-1} aria-hidden="true"><img className="search-thumbnail" src={hit.thumbnailUrl} alt="" width={96} height={112} loading="lazy" decoding="async"/></a>}</article>)}{!busy&&data&&!data.results.length&&<p className="search-empty">일치하는 자료가 없습니다. 검색어를 줄이거나 필터를 해제해 보세요.</p>}</section>}
 {data?.related?.length? <div className="search-related">관련 용어 {data.related.map(t=><button key={t} onClick={()=>search(t)}>{t}</button>)}</div>:null}
 <nav className="search-pages" aria-label="검색 결과 페이지">{p.has('cursor')&&<button onClick={()=>window.history.back()}>← 이전 페이지</button>}{data?.nextCursor&&<button disabled={busy} onClick={()=>{const next=new URLSearchParams(params);next.set('cursor',data.nextCursor!);navigate(next);document.getElementById('explore')?.scrollIntoView();}}>다음 20개 →</button>}</nav>
 </main>;
}
