import {unzipSync,strFromU8} from 'fflate';
import {parse} from 'parse5';
import {XMLParser} from 'fast-xml-parser';
import {createRequire} from 'node:module';
import path from 'node:path';
const require=createRequire(import.meta.url),MAX_BYTES=16*1024*1024;
export const PROCESSOR_VERSION='dcl-extractor-2.0.1';
export function safeZip(bytes){let total=0,count=0;const files=unzipSync(bytes,{filter:file=>{if(++count>256)throw new Error('압축 항목 256개 한도');total+=file.originalSize;if(total>MAX_BYTES)throw new Error('압축 해제 16MB 한도');if(file.name.endsWith('/'))return false;if(!file.name||file.name.startsWith('/')||/[\\:?#]/.test(file.name)||file.name.split('/').some(p=>!p||p==='..')||Array.from(file.name).some(c=>c.charCodeAt(0)<32))throw new Error('안전하지 않은 압축 경로');return !file.name.startsWith('__MACOSX/');}});if(Object.values(files).reduce((n,v)=>n+v.length,0)>MAX_BYTES)throw new Error('압축 해제 한도');return files;}
export function htmlText(html){const document=parse(html);const chunks=[];function visit(node){if(['script','style','noscript','template','iframe'].includes(node.tagName))return;if(node.nodeName==='#text')chunks.push(node.value);for(const c of node.childNodes||[])visit(c);if(['p','div','li','h1','h2','h3','tr','br'].includes(node.tagName))chunks.push('\n');}visit(document);return chunks.join(' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').trim();}
function xml(bytes){const value=strFromU8(bytes);if(/<!DOCTYPE|<!ENTITY/i.test(value))throw new Error('외부 XML 엔터티 미지원');if(value.length>MAX_BYTES)throw new Error('XML 크기 한도');return new XMLParser({preserveOrder:true,ignoreAttributes:false,processEntities:false,parseTagValue:false,parseAttributeValue:false,trimValues:false}).parse(value);}
function textNodes(nodes,depth=0){if(depth>80)throw new Error('XML 중첩 한도');const result=[];for(const node of Array.isArray(nodes)?nodes:[]){for(const [key,val]of Object.entries(node)){if(key==='#text')result.push(String(val).replace(/&(#x[0-9a-f]+|#[0-9]+|lt|gt|amp|quot|apos);/gi,(_,v)=>{const predefined={lt:'<',gt:'>',amp:'&',quot:'"',apos:"'"};if(predefined[v])return predefined[v];const n=v.startsWith('#x')?parseInt(v.slice(2),16):parseInt(v.slice(1),10);return n>0&&n<=0x10ffff&&!(n>=0xd800&&n<=0xdfff)?String.fromCodePoint(n):'�';}));else if(key!==':@'){result.push(textNodes(val,depth+1));if(/(^|:)(p|tr|row|br|tab)$/.test(key))result.push('\n');}}}return result.join('');}
function attributes(nodes,local){const result=[];for(const node of Array.isArray(nodes)?nodes:[])for(const[key,val]of Object.entries(node)){if(key.split(':').pop()===local)result.push(node[':@']||{});if(Array.isArray(val))result.push(...attributes(val,local));}return result;}
function entries(nodes,local){const result=[];for(const node of Array.isArray(nodes)?nodes:[])for(const[key,val]of Object.entries(node)){if(key.split(':').pop()===local)result.push({nodes:val,attrs:node[':@']||{}});else if(Array.isArray(val))result.push(...entries(val,local));}return result;}
function officeSections(files,name){
 if(/\.docx$/i.test(name)){return ['word/document.xml',...Object.keys(files).filter(p=>/^word\/(header\d+|footer\d+|footnotes|endnotes)\.xml$/.test(p)).sort()].filter(p=>files[p]).map(p=>({text:textNodes(xml(files[p])),path:p}));}
 if(/\.pptx$/i.test(name)){const rels=files['ppt/_rels/presentation.xml.rels']?attributes(xml(files['ppt/_rels/presentation.xml.rels']),'Relationship'):[];const order=files['ppt/presentation.xml']?attributes(xml(files['ppt/presentation.xml']),'sldId'):[];const paths=order.map(a=>rels.find(r=>r['@_Id']===a['@_r:id'])?.['@_Target']).filter(Boolean).map(p=>path.posix.normalize('ppt/'+p)).filter(p=>files[p]);if(!paths.length)paths.push(...Object.keys(files).filter(p=>/^ppt\/slides\/slide\d+\.xml$/.test(p)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})));return paths.map((p,i)=>({text:textNodes(xml(files[p])),page:i+1,path:p}));}
 if(/\.xlsx$/i.test(name)){const shared=files['xl/sharedStrings.xml']?entries(xml(files['xl/sharedStrings.xml']),'si').map(s=>textNodes(s.nodes)):[];const rels=files['xl/_rels/workbook.xml.rels']?attributes(xml(files['xl/_rels/workbook.xml.rels']),'Relationship'):[];const sheets=files['xl/workbook.xml']?attributes(xml(files['xl/workbook.xml']),'sheet'):[];return sheets.map(sheet=>{const target=rels.find(r=>r['@_Id']===sheet['@_r:id'])?.['@_Target'];const p=target?.startsWith('/')?target.slice(1):path.posix.normalize('xl/'+target);if(!files[p])return {text:'',path:p};const rows=entries(xml(files[p]),'row').map(row=>entries(row.nodes,'c').map(cell=>{const value=entries(cell.nodes,'v').map(v=>textNodes(v.nodes)).join('');const formula=entries(cell.nodes,'f').map(v=>'='+textNodes(v.nodes)).join('');return cell.attrs['@_r']+': '+(cell.attrs['@_t']==='s'?(shared[Number(value)]||''):cell.attrs['@_t']==='inlineStr'?textNodes(cell.nodes):[value,formula].filter(Boolean).join(' '));}).join('\t'));return {text:String(sheet['@_name'])+'\n'+rows.join('\n'),path:p};});}
 if(/\.hwpx$/i.test(name)){let paths=[];if(files['Contents/content.hpf']){const hpf=xml(files['Contents/content.hpf']),items=attributes(hpf,'item');paths=attributes(hpf,'itemref').map(a=>items.find(i=>i['@_id']===a['@_idref'])?.['@_href']).filter(Boolean).map(p=>p.startsWith('Contents/')?p:path.posix.normalize('Contents/'+p)).filter(p=>files[p]&&/section\d+\.xml$/.test(p));}if(!paths.length)paths=Object.keys(files).filter(p=>/^Contents\/section\d+\.xml$/.test(p)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));return paths.map(p=>({text:textNodes(xml(files[p])),path:p}));}
 return [];
}
export async function createExtractor({cachePath,ocr='auto'}={}){
 let worker;async function recognize(image){worker||=await (await import('tesseract.js')).createWorker(['kor','eng'],1,{cachePath});let timer;const pending=worker.recognize(image,{}, {text:true});let result;try{result=await Promise.race([pending,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('OCR 시간 한도 120초')),120000)})]);}catch(error){await worker.terminate();worker=undefined;throw error;}finally{clearTimeout(timer);}return {text:result.data.text,confidence:result.data.confidence};}
 async function previews(canvas){const native=await import('@napi-rs/canvas');const output={};for(const[k,edge]of [['thumbnail',240],['preview',1400]]){const ratio=Math.min(1,edge/Math.max(canvas.width,canvas.height));const c=native.createCanvas(Math.max(1,Math.round(canvas.width*ratio)),Math.max(1,Math.round(canvas.height*ratio)));c.getContext('2d').drawImage(canvas,0,0,c.width,c.height);output[k]=await c.encode('webp',78);}return output;}
 async function* extract(bytes,name,{skipPages=0,depth=0}={}){
  if(bytes.length>20*1024*1024)throw new Error('원본 20MB 한도');
  if(/\.pdf$/i.test(name)){
   const pdf=await import('pdfjs-dist/legacy/build/pdf.mjs'),root=path.dirname(require.resolve('pdfjs-dist/package.json'));const task=pdf.getDocument({data:new Uint8Array(bytes),cMapUrl:root+'/cmaps/',cMapPacked:true,standardFontDataUrl:root+'/standard_fonts/',wasmUrl:root+'/wasm/',maxImageSize:16000000});
   try{const doc=await task.promise;for(let i=skipPages+1;i<=doc.numPages;i++){const page=await doc.getPage(i);let target,nativeText='',images;try{const content=await page.getTextContent();nativeText=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('');const operators=await page.getOperatorList();const hasRaster=operators.fnArray.some(x=>[pdf.OPS.paintImageXObject,pdf.OPS.paintInlineImageXObject,pdf.OPS.paintImageMaskXObject].includes(x));const needsOcr=ocr==='force'||(ocr!=='off'&&(hasRaster||nativeText.trim().length<40));let text=nativeText,method='pdf-text',confidence,warnings=[];
    if(needsOcr||i===1){const base=page.getViewport({scale:1}),scale=Math.min(2.5,Math.sqrt(16000000/(base.width*base.height))),viewport=page.getViewport({scale});target=doc.canvasFactory.create(Math.ceil(viewport.width),Math.ceil(viewport.height));await page.render({canvas:target.canvas,canvasContext:target.context,viewport}).promise;if(i===1)images=await previews(target.canvas);if(needsOcr){const recognized=await recognize(await target.canvas.encode('png'));text=nativeText+'\n'+recognized.text;method='pdf-text+ocr';confidence=recognized.confidence;if(confidence<55)warnings.push('OCR 인식 신뢰도가 낮은 페이지');}}
    if(!text.trim())warnings.push('읽을 수 있는 본문이 없는 페이지');if(ocr==='off'&&hasRaster)warnings.push('이미지 영역 OCR 생략');yield {text,page:i,path:name,method,confidence,warnings,previews:images,totalPages:doc.numPages};
   }catch(error){yield{text:nativeText,page:i,path:name,previews:images,method:nativeText?'pdf-text':'failed',warnings:['이 페이지를 읽지 못했습니다: '+String(error.message).slice(0,100)]};}finally{if(target)doc.canvasFactory.destroy(target);page.cleanup();}}}finally{await task.destroy();}return;
  }
  if(/\.(png|jpe?g|webp|bmp|gif|tiff?)$/i.test(name)){const native=await import('@napi-rs/canvas'),image=await native.loadImage(bytes);if(image.width*image.height>25000000)throw new Error('이미지 픽셀 한도');const c=native.createCanvas(image.width,image.height);c.getContext('2d').drawImage(image,0,0);const images=await previews(c);if(ocr==='off'){yield {text:'',path:name,previews:images,warnings:['OCR 꺼짐'],unsupported:true};return;}const result=await recognize(await c.encode('png'));yield {...result,page:1,path:name,method:'ocr',previews:images,warnings:result.confidence<55||!result.text.trim()?['OCR 결과를 확인해 주세요.']:[]};return;}
  if(/\.(docx|pptx|xlsx|hwpx)$/i.test(name)){const sections=officeSections(safeZip(bytes),name);if(!sections.length){yield{text:'',path:name,unsupported:true,warnings:['읽을 수 있는 문서 본문이 없습니다.']};return;}for(const section of sections)yield {...section,method:'office-xml',warnings:[]};return;}
  if(/\.zip$/i.test(name)){if(depth>=2)throw new Error('중첩 ZIP 두 단계 한도');const files=safeZip(bytes);for(const [p,file]of Object.entries(files)){try{for await(const section of extract(file,p,{depth:depth+1}))yield {...section,path:name+'/'+(section.path||p)};}catch{yield{text:'',path:name+'/'+p,unsupported:true,warnings:['압축 내부 파일을 읽지 못했습니다.']};}}return;}
  if(/\.(txt|md|markdown|js|jsx|ts|tsx|py|java|c|cpp|h|cs|go|rs|rb|php|sh|sql|json|csv|tsv|xml|yaml|yml|css|html?|svg|log|ipynb)$/i.test(name)){const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);yield{text:/\.html?$/i.test(name)?htmlText(text):text,path:name,line:1,method:'text',warnings:[]};return;}
  yield{text:'',path:name,unsupported:true,warnings:['미지원 형식: 원본 다운로드로 열 수 있습니다.']};
 }
 return {extract,close:async()=>{await worker?.terminate();}};
}
